### ISSUE TITLE
which version should  i3-7100u install?

### ISSUE THREAD

**Issue by yyysuo** [NeverEatYellowSwissSnow/synology-dsm-open-vm-tools#2]
I install dsm in esxi 6.7 update3, Which version should I install? thank you very much.

**Comment by Grandma-Betty** [comment]
> 
> 
> I install dsm in esxi 6.7 update3, Which version should I install? thank you very much.

Your physical CPU generation does not matter for choosing the right open-vm-tools version. It depends on the underlying virtual CPU generation of your DSM installation you have chosen with your loader version when setting up your XPEnology system for the first time.
_DS918+_ is Apollolake generation, so you would have to take **open-vm-tools_apollolake-6.2_11.2.5-1.spk**
_DS3617xs_ is Broadwell generation, so you would have to take **open-vm-tools_broadwell-6.2_11.2.5-1.spk**

**Comment by yyysuo** [comment]
thanks again,it works fine.
